Flowplan implementation, plug-in refactor

diff --git a/deltafi-cli/commands/install-plugin b/deltafi-cli/commands/install-plugin
--- a/deltafi-cli/commands/install-plugin
+++ b/deltafi-cli/commands/install-plugin
@@ -10,19 +10,30 @@ Usage:
   install-plugin PLUGIN_DIRECTORY [OPTIONS] [helm flags]
 
 Options:
-  -l, --load-flows Load flows included with plugin (if present)
-  -h, --help       Show help"
+  -h, --help        Show help
+  -v, --verbose     Verbose output"
   exit 1
 }
 
-LOAD_FLOWS=false
+TMP_SOURCE_PLUGIN_FILE="/tmp/.deltafi-source-plugin.$$"
+TMPFILE="/tmp/.deltafi-register-plugin-manifest.$$"
+
+cleanup() {
+  rm -f $TMP_SOURCE_PLUGIN_FILE
+  rm -f $TMPFILE
+  exit
+}
+
+trap cleanup INT
+
+VERBOSE=false
 
 POSITIONAL=()
 while [[ $# -gt 0 ]]; do
   key="$1"
   case $key in
-    -l|--load-flows)
-      LOAD_FLOWS=true
+    -v|--verbose)
+      VERBOSE=true
       shift
       ;;
     *)
@@ -38,24 +49,43 @@ ARGS=($@)
 
 PLUGIN_DIRECTORY=${ARGS[1]}
 if [ ! -d "$PLUGIN_DIRECTORY" ]; then
-  cli_log "${red}${PLUGIN_DIRECTORY}: Plugin directory not found${normal}"
+  cli_log "${red}$PLUGIN_DIRECTORY: Plugin directory not found${normal}"
   exit 1
 fi
 PLUGIN_DIRECTORY=$(cd $PLUGIN_DIRECTORY && pwd)
 
 CHARTS_DIRECTORY="$PLUGIN_DIRECTORY/charts"
 if [ ! -d "$CHARTS_DIRECTORY" ]; then
-  cli_log "${red}${PLUGIN_DIRECTORY}: Plugin directory does not include a ${bold}charts${normal}${red} subdirectory${normal}"
+  cli_log "${red}$PLUGIN_DIRECTORY: Plugin directory does not include a ${bold}charts${normal}${red} subdirectory${normal}"
   exit 1
 fi
 
 CHART_YAML="$CHARTS_DIRECTORY/Chart.yaml"
 if [ ! -f "$CHART_YAML" ]; then
-  cli_log "${red}${PLUGIN_DIRECTORY}: Plugin missing ${bold}charts/Chart.yaml${normal}"
+  cli_log "${red}$PLUGIN_DIRECTORY: Plugin missing ${bold}charts/Chart.yaml${normal}"
   exit 1
 fi
 
 PLUGIN_NAME="$(grep -e '^name:' ${CHART_YAML} | awk '{print $2}')"
+
+cli_log "${bold}$PLUGIN_NAME${normal}: Registering plugin manifest"
+PLUGIN_MANIFEST="$CHARTS_DIRECTORY/files/plugin.json"
+if [ ! -f "$PLUGIN_MANIFEST" ]; then
+  cli_log "${red}$PLUGIN_DIRECTORY: Plugin manifest (plugin.json) not found in ${bold}.plugin${normal}${red} subdirectory. Make sure the project uses the generate-plugin-manifest gradle plugin.${normal}"
+  exit 1
+fi
+
+load_plan() {
+  if [[ ! "${1}" =~ "variables.json" ]]; then
+    deltafi load-plan $1 $2
+  fi
+}
+
+fail() {
+  cli_log "${red}$PLUGIN_DIRECTORY: $1${normal}"
+  echo -e "${red}Error: $2${normal}"
+  cleanup
+}
 
 cli_log "${bold}$PLUGIN_NAME${normal}: Installing plugin"
 helm upgrade --install --wait \
@@ -66,14 +96,23 @@ helm upgrade --install --wait \
 HELM_RETURN_CODE=$?
 [[ "$HELM_RETURN_CODE" != "0" ]] && exit $HELM_RETURN_CODE
 
-if [[ "$LOAD_FLOWS" == true ]]; then
-  FLOWS_DIRECTORY="$PLUGIN_DIRECTORY/flows"
-  if [ ! -d "$FLOWS_DIRECTORY" ]; then
-    cli_log "${yellow}${PLUGIN_NAME}: Plugin directory does not include a ${bold}flows${normal}${yellow} subdirectory${normal}"
-  else
-    cli_log "${bold}$PLUGIN_NAME${normal}: Loading plugin flows"
-    find $FLOWS_DIRECTORY -name *.y*ml -exec deltafi load-config {} \;
+FLOWS_DIRECTORY="$PLUGIN_DIRECTORY/flows"
+if [ ! -d "$FLOWS_DIRECTORY" ]; then
+  cli_log "${yellow}$PLUGIN_NAME: Plugin directory does not include a ${bold}flows${normal}${yellow} subdirectory${normal}"
+else
+  cli_log "${bold}$PLUGIN_NAME${normal}: Loading plugin flow plans ... waiting for action registration"
+  sleep 15
+
+  JSON=$(cat "$PLUGIN_MANIFEST")
+  echo $JSON | jq -r '.pluginCoordinates' > $TMP_SOURCE_PLUGIN_FILE
+  export -f load_plan
+
+  if [[ -f $FLOWS_DIRECTORY/variables.json ]]; then
+    deltafi load-variables "${FLOWS_DIRECTORY}/variables.json" "$TMP_SOURCE_PLUGIN_FILE"
   fi
+
+  find $FLOWS_DIRECTORY -name *.json -exec bash -c "load_plan \"{}\" \"$TMP_SOURCE_PLUGIN_FILE\"" \;
 fi
 
 cli_log "${bold}$PLUGIN_NAME${normal}: Plugin install complete."
+cleanup
diff --git a/deltafi-cli/commands/load-plan b/deltafi-cli/commands/load-plan
--- a/deltafi-cli/commands/load-plan
+++ b/deltafi-cli/commands/load-plan
@@ -20,7 +20,6 @@ cleanup() {
 
 trap cleanup INT
 
-MUTATION="saveFlowPlan"
 POSITIONAL=()
 while [[ $# -gt 0 ]]; do
   key="$1"
@@ -41,18 +40,36 @@ set -- "${POSITIONAL[@]}" # restore positional parameters
 ARGS=($@)
 [[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command
 [[ ${#ARGS[@]} -lt 2 ]] && cli_help_command
-FILE=${ARGS[@]:1}
+FLOW_PLAN_FILE=${ARGS[1]}
+SOURCE_PLUGIN_FILE=${ARGS[2]}
 
-if [ ! -f "$FILE" ]; then
-  cli_log "${yellow}${FILE}: No such file${normal}"
+if [ ! -f "$FLOW_PLAN_FILE" ]; then
+  cli_log "${yellow}${FLOW_PLAN_FILE}: No such file${normal}"
   exit 1
 fi
 
-BASENAME="$(basename $FILE)"
-JSON=$(cat "$FILE")
+BASENAME="$(basename $FLOW_PLAN_FILE)"
+JSON=$(cat "$FLOW_PLAN_FILE")
+
+if [ -f "$SOURCE_PLUGIN_FILE" ] && [ "$( jq 'has("sourcePlugin")' <<< $JSON )" == "false" ]; then
+  SOURCE_PLUGIN=$(cat "$SOURCE_PLUGIN_FILE")
+  JSON=$(echo "$JSON" | jq --argjson json "$SOURCE_PLUGIN" '. + {sourcePlugin: $json}')
+fi
+
 VARIABLES="{\"flowPlan\": $JSON }"
 
-QUERY="mutation(\$flowPlan: FlowPlanInput!) {${MUTATION}(flowPlan: \$flowPlan) { name }}"
+if [[ "$JSON" == *"loadAction"* ]]; then
+  OPERATION_NAME="saveIngressFlowPlan"
+  QUERY="mutation(\$flowPlan: IngressFlowPlanInput!) {saveIngressFlowPlan(ingressFlowPlan: \$flowPlan) { name }}"
+elif [[ "$JSON" == *"egressAction"* ]]; then
+  OPERATION_NAME="saveEgressFlowPlan"
+  QUERY="mutation(\$flowPlan: EgressFlowPlanInput!) {saveEgressFlowPlan(egressFlowPlan: \$flowPlan) { name }}"
+else
+  cli_log "${red}${BASENAME}: Loading flow plan failed, the plan must contain a load action or egress action${normal}"
+  echo -e "${red}Loading flow plan failed, plan must contain a load action or egress action${normal}"
+  exit 1
+fi
+
 DELTAFI_DGS=$(deltafi serviceip deltafi-core-domain-service)
 POST_QUERY="{ \"query\": \"$QUERY\",\"variables\":$VARIABLES}"
 
@@ -68,7 +85,8 @@ else
     cli_log "${red}${BASENAME}: Loading flow plan failed${normal}"
     echo -e "${red}Error: ${ERRORS}${normal}"
   else
-    cli_log "Successfully loaded flow plan from file ${cyan}${BASENAME}${normal}"
+    LOADED=$(cat ${TMPFILE} | jq -r ".data.${OPERATION_NAME}.name")
+    cli_log "Successfully loaded flow plan ${LOADED} from file ${cyan}${BASENAME}${normal}"
   fi
 fi
 
diff --git a/deltafi-cli/commands/uninstall-plugin b/deltafi-cli/commands/uninstall-plugin
--- a/deltafi-cli/commands/uninstall-plugin
+++ b/deltafi-cli/commands/uninstall-plugin
@@ -7,13 +7,55 @@ cli_help_command() {
 Command: uninstall-plugin
 
 Usage:
-  uninstall-plugin PLUGIN_DIRECTORY [helm flags]"
+  uninstall-plugin PLUGIN_DIRECTORY [OPTIONS] [helm flags]
+
+Options:
+  --dry-run         Simulate the helm uninstall
+  -h, --help        Show help
+  -f, --force       Force helm uninstall"
   exit 1
 }
 
+HELMDRYRUN=false
+FORCE=false
+
+POSITIONAL=()
+while [[ $# -gt 0 ]]; do
+  key="$1"
+  case $key in
+    -f|--force)
+      FORCE=true
+      shift
+      ;;
+    *)
+      POSITIONAL+=("$1")
+      shift
+      ;;
+  esac
+done
+set -- "${POSITIONAL[@]}"
 ARGS=($@)
 [[ " ${ARGS[@]} " =~ " --help " ]] && cli_help_command
 [[ ${#ARGS[@]} -lt 2 ]] && cli_help_command
+[[ " ${ARGS[@]} " =~ " --dry-run " ]] && HELMDRYRUN=true
+
+TMPFILE="/tmp/.deltafi-uninstall-plugin.$$"
+FORCEAFTERERROR=false
+
+cleanup() {
+  rm -f $TMPFILE
+  exit
+}
+
+log_failed() {
+  cli_log "${red}${BASENAME}: Plugin cannot be removed${normal}"
+  echo -e "${red}Error: ${1}${normal}"
+  if [[ $FORCE == "true" ]]; then
+    FORCEAFTERERROR=true
+  else
+    cleanup
+  fi
+}
 
 PLUGIN_DIRECTORY=${ARGS[1]}
 if [ ! -d "$PLUGIN_DIRECTORY" ]; then
@@ -35,5 +77,63 @@ fi
 
 PLUGIN_NAME="$(grep -e '^name:' ${CHART_YAML} | awk '{print $2}')"
 
-cli_log "Uninstalling ${PLUGIN_NAME} plugin"
+PLUGIN_MANIFEST="$CHARTS_DIRECTORY/files/plugin.json"
+if [ ! -f "$PLUGIN_MANIFEST" ]; then
+  cli_log "${red}$PLUGIN_DIRECTORY: Plugin manifest (plugin.json) not found in ${bold}.plugin${normal}${red} subdirectory. Make sure the project uses the generate-plugin-manifest gradle plugin.${normal}"
+  exit 1
+fi
+
+DGSVARDRYRUN=true
+PLUGIN_ID=$(cat ${PLUGIN_MANIFEST} | jq -r '.pluginCoordinates')
+
+uninstallPlugin() {
+  MUTATION="uninstallPlugin"
+  DELTAFI_DGS=$(deltafi serviceip deltafi-core-domain-service)
+  QUERY="mutation (\$pluginId: PluginCoordinatesInput!) {$MUTATION(dryRun: $DGSVARDRYRUN, pluginCoordinatesInput: \$pluginId) {success errors}}"
+  VARIABLES=$(echo "{}" |  jq --argjson pluginId "$PLUGIN_ID" '. + {pluginId: $pluginId}')
+  POST_QUERY="{ \"query\": \"$QUERY\",\"variables\":$VARIABLES}"
+
+  truncate --size 0 ${TMPFILE}
+  RESPONSE_CODE=$(curl -s -X POST -o ${TMPFILE} -w "%{http_code}" -H "Content-Type: application/json" -d "$POST_QUERY" http://$DELTAFI_DGS/graphql)
+
+  if [[ "$RESPONSE_CODE" != "200" ]]; then
+    ERRORS=$(cat ${TMPFILE})
+    log_failed "$ERRORS"
+  else
+    DGS_ERRORS=$(cat ${TMPFILE} | jq -r "select(.errors) | .errors[] | .message")
+    if [[ "$DGS_ERRORS" != "" ]]; then
+      log_failed "$DGS_ERRORS"
+    else
+      SUCCESS=$(cat ${TMPFILE} | jq -r '.data.uninstallPlugin.success')
+      if [[ $SUCCESS == "true" ]]; then
+        if [[ $DGSVARDRYRUN == "true" ]]; then
+          cli_log "Safe to remove plugin"
+        fi
+      else
+        ERRORS=$(cat ${TMPFILE} | jq -r '.data.uninstallPlugin.errors | join(",")')
+        log_failed "$ERRORS"
+      fi
+    fi
+  fi
+}
+
+cli_log "Checking to see if plugin can be safely uninstalled"
+uninstallPlugin
+
+if [[ $FORCEAFTERERROR == "true" ]]; then
+  cli_log "Forcing removal of the plugin from the cluster"
+  helm uninstall ${PLUGIN_NAME} ${ARGS[@]:2}
+  cleanup
+fi
+
+cli_log "Removing the plugin from the cluster"
 helm uninstall ${PLUGIN_NAME} ${ARGS[@]:2}
+
+if [[ $HELMDRYRUN == "false" ]]; then
+  cli_log "Removing the plugin from the DeltaFi Plugin registry"
+  DGSVARDRYRUN=false
+  uninstallPlugin
+  cli_log "Plugin ${PLUGIN_NAME} has been successfully uninstalled"
+fi
+
+cleanup
diff --git a/gradle-plugin/src/main/resources/job-register-plugin.yaml b/gradle-plugin/src/main/resources/job-register-plugin.yaml
--- a/gradle-plugin/src/main/resources/job-register-plugin.yaml
+++ b/gradle-plugin/src/main/resources/job-register-plugin.yaml
@@ -4,7 +4,7 @@ metadata:
   name: register-deltafi-plugin
   annotations:
     "helm.sh/hook": pre-install,pre-upgrade
-    "helm.sh/hook-delete-policy": hook-succeeded
+    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
 spec:
   template:
     spec:
@@ -17,16 +17,32 @@ spec:
         - "-c"
         - |
           echo "Registering {{ .Chart.Name }} plugin..."
-          MUTATION="mutation(\$pluginInput: PluginInput!) {registerPlugin(pluginInput: \$pluginInput) {pluginCoordinates {artifactId}}}"
+          TMPFILE=/tmp/register_response
+          MUTATION="mutation(\$pluginInput: PluginInput!) {registerPlugin(pluginInput: \$pluginInput) {success errors}}"
           JSON={{ .Files.Get "files/plugin.json" | replace "\n" "" | quote}}
           VARIABLES="{\"pluginInput\": $JSON}"
           POST_QUERY="{\"query\": \"$MUTATION\", \"variables\":$VARIABLES}"
           echo "Sending $POST_QUERY"
-          RESPONSE_CODE=$(curl -s -o /tmp/register_response -X POST -w "%{http_code}" -H "Content-Type: application/json" -d "$POST_QUERY" http://deltafi-core-domain-service/graphql)
+          RESPONSE_CODE=$(curl -s -o ${TMPFILE} -X POST -w "%{http_code}" -H "Content-Type: application/json" -d "$POST_QUERY" http://deltafi-core-domain-service/graphql)
           if [[ "$RESPONSE_CODE" != "200" ]]; then
-            echo "Registering plugin manifest failed" "Bad response code ($RESPONSE_CODE) with response $(cat /tmp/register_response)"
+            echo "Registering plugin manifest failed" "Bad response code ($RESPONSE_CODE) with response $(cat ${TMPFILE})"
             exit 1
           fi
+
+          DGS_ERRORS=$(cat ${TMPFILE} | jq -r "select(.errors) | .errors[] | .message")
+          if [[ "$DGS_ERRORS" != "" ]]; then
+            echo "Registering plugin manifest failed" "$DGS_ERRORS"
+            exit 1
+          fi
+
+          SUCCESS=$(cat ${TMPFILE} | jq -r '.data.registerPlugin.success')
+          if [[ $SUCCESS == "false" ]]; then
+            ERRORS=$(cat ${TMPFILE} | jq -r '.data.registerPlugin.errors | join(",")')
+            echo "Registering plugin manifest failed ${ERRORS}"
+            exit 1
+          fi
+
           cat /tmp/register_response
           echo "Success"
       restartPolicy: Never
+  backoffLimit: 0
