Refactor KinD gradle workflow and image caching/loading

diff --git a/orchestration/kind/cluster b/orchestration/kind/cluster
--- a/orchestration/kind/cluster
+++ b/orchestration/kind/cluster
@@ -342,63 +342,21 @@ EOF
   _ok "Updated k8s configuration file permissions"
 }
 
-_create_proxy() {
-  local PROXY_NAME=$1
-  local PROXY_REMOTE=$2
-  local PROXY_PORT=$3
+_create_volume() {
+  local VOLUME_NAME=$1
   # Create volume if not present
-  if ! docker volume inspect "$PROXY_NAME" > /dev/null 2>/dev/null; then
-    docker volume create "$PROXY_NAME" > /dev/null
-    _ok "Created docker volume for $PROXY_NAME"
-  fi
-  running="$(docker container inspect -f '{{.State.Running}}' "${PROXY_NAME}" 2>/dev/null || true > /dev/null)"
-  if [ "${running}" != 'true' ]; then
-      docker run \
-            -d --name "${PROXY_NAME}" \
-            --restart=always --net=kind \
-            --mount source="${PROXY_NAME}",destination=/var/lib/registry \
-            -e REGISTRY_PROXY_REMOTEURL="${PROXY_REMOTE}" \
-            -p "127.0.0.1:${PROXY_PORT}:5000" \
-            registry:2 > /dev/null
-      _ok "Created registry proxy container: $PROXY_NAME"
+  if ! docker volume inspect "VOLUME_NAME" > /dev/null 2>/dev/null; then
+    docker volume create "$VOLUME_NAME" > /dev/null
+    _ok "Created docker volume for $VOLUME_NAME"
   fi
 }
 
-_destroy_proxy() {
-  local PROXY_NAME=$1
-  _attention "Destroying $PROXY_NAME proxy"
-  if docker container inspect "$PROXY_NAME" > /dev/null 2>/dev/null; then
-    if [ "$(docker container inspect -f '{{.State.Running}}' ${PROXY_NAME})" == 'true' ]; then
-
-      _info "Stopping $PROXY_NAME"
-      docker stop "$PROXY_NAME" > /dev/null
-    fi
-    _info "Removing $PROXY_NAME container"
-    docker rm "$PROXY_NAME" > /dev/null
-  fi
-  if docker volume inspect "$PROXY_NAME" > /dev/null 2>/dev/null; then
-    _info "Removing $PROXY_NAME volume"
-    docker volume rm "$PROXY_NAME" > /dev/null
-  fi
-}
-
-_create_registry() {
-  local REGISTRY_NAME=$1
-  local REGISTRY_PORT=$2
+_destroy_volume() {
+  local VOLUME_NAME=$1
   # Create volume if not present
-  if ! docker volume inspect "$REGISTRY_NAME" 2>/dev/null > /dev/null; then
-    docker volume create "$REGISTRY_NAME" > /dev/null
-    _ok "Created volume for KinD docker registry: $REGISTRY_NAME"
-  fi
-  running="$(docker inspect -f '{{.State.Running}}' "${REGISTRY_NAME}" 2>/dev/null || true)"
-  if [ "${running}" != 'true' ]; then
-      docker run \
-            -d --name "${REGISTRY_NAME}" \
-            --restart=always --net=kind \
-            --mount source="${REGISTRY_NAME}",destination=/var/lib/registry \
-            -p "127.0.0.1:${REGISTRY_PORT}:5000" \
-            registry:2 > /dev/null
-      _ok "Created KinD docker registry: $REGISTRY_NAME"
+  if docker volume inspect "VOLUME_NAME" > /dev/null 2>/dev/null; then
+    docker volume rm "$VOLUME_NAME" > /dev/null
+    _ok "Removed docker volume for $VOLUME_NAME"
   fi
 }
 
@@ -408,7 +366,7 @@ _install_plugins() {
     image=$(_plugin_field "$plugin" "image")
 
     if [[ $image == null ]]; then
-      image="localhost:5000/$plugin"
+      image="deltafi/$plugin"
     fi
 
     local imagePullSecret
@@ -483,14 +441,9 @@ prerequisites() {
 
 describe destroy_registries "Scorched earth clean up of all KinD registries"
 destroy_registries() {
-  [[ $# -gt 0 && "$1" == '-f' ]] || _are_you_sure "Do you want to delete all KinD docker registry proxies?"
-  _warn "Destroying KinD docker registry proxies"
-  _destroy_proxy kind-registry
-  _destroy_proxy dockerio-proxy
-  _destroy_proxy k8s-proxy
-  _destroy_proxy ghcr-proxy
-  _destroy_proxy quay-proxy
-  _destroy_proxy k8s-registry-proxy
+  [[ $# -gt 0 && "$1" == '-f' ]] || _are_you_sure "Do you want to delete all KinD docker registry cache?"
+  _warn "Destroying KinD docker registry cache"
+  _destroy_volume "deltafi-kind-cache"
 }
 
 describe up "Turn up a KinD cluster (or re-apply cluster settings)"
@@ -511,12 +464,7 @@ up() {
   fi
   pushd "$BASE_PATH" > /dev/null
 
-  _create_registry kind-registry 5000
-  _create_proxy dockerio-proxy "https://registry-1.docker.io" 5001
-  _create_proxy k8s-proxy "https://k8s.gcr.io" 5002
-  _create_proxy ghcr-proxy "https://ghcr.io" 5003
-  _create_proxy quay-proxy "https://quay.io" 5004
-  _create_proxy k8s-registry-proxy "https://registry.k8s.io" 5005
+  _create_volume deltafi-kind-cache
 
   if kind get clusters -q | grep "^${CLUSTER_NAME}$" > /dev/null; then
     _ok "KinD ${CLUSTER_NAME} cluster already instantiated"
@@ -545,23 +493,11 @@ nodes:
     containerPath: /usr/dev
   - hostPath: "${PV_DIR}"
     containerPath: /data/deltafi
-containerdConfigPatches:
-- |-
-  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
-    endpoint = ["http://dockerio-proxy:5000"]
-  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."k8s.gcr.io"]
-    endpoint = ["http://k8s-proxy:5000"]
-  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."ghcr.io"]
-    endpoint = ["http://ghcr-proxy:5000"]
-  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
-    endpoint = ["http://quay-proxy:5000"]
-  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
-    endpoint = ["http://kind-registry:5000"]
-  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."local.plugin.registry"]
-    endpoint = ["http://local.plugin.registry"]
-  [plugins."io.containerd.grpc.v1.cri".registry.configs."local.plugin.registry".auth]
-    username = "deltafi"
-    password = "password"
+  - hostPath: "/var/lib/docker/volumes/deltafi-kind-cache/_data"
+    containerPath: /var/lib/containerd
+    readOnly: false
+    selinuxRelabel: false
+    propagation: None
 EOF
     _ok "${CLUSTER_NAME} cluster instantiated"
   fi
@@ -771,10 +707,6 @@ destroy() {
 
   destroy_registries "$@"
 
-  local images=$(docker images | grep ^localhost:5000 | awk '{print $3}')
-  _annotated_subshell -h "Pruning localhost:5000 images" docker rmi ${images} || true
-  _ok_annotated "Pruned localhost:5000 images"
-
   _down "KinD cluster destroyed"
 }
 
@@ -972,7 +904,7 @@ loc() {
 
   if [[ -n "$INSTALL" || -n "$REINSTALL" || -n "$RESTART" ]]; then
     _attention "Installing DeltaFi core"
-    install -f deltafi/orchestration/charts/deltafi/values-kind.yaml -f deltafi/orchestration/charts/deltafi/values-local.yaml -f deltafi/orchestration/charts/deltafi/values-alerting-test.yaml
+    install -f deltafi/orchestration/charts/deltafi/values-kind.yaml -f deltafi/orchestration/charts/deltafi/values-alerting-test.yaml
 
     _install_plugins
   fi
@@ -1021,7 +953,7 @@ _plugin_clean() {
 _do_plugin_build() {
   _attention "Building $plugin"
   if _has_gradle; then
-    ./gradlew "${BUILD_TARGETS[@]}" -x test docker dockerPushLocal || _exit_1 echo "Command 'gradlew \"${BUILD_TARGETS[@]}\" -x test docker dockerPushLocal' failed"
+    ./gradlew "${BUILD_TARGETS[@]}" -x test docker install || _exit_1 echo "Command 'gradlew \"${BUILD_TARGETS[@]}\" -x test docker install' failed"
   elif _has_makefile; then
     make dockerPushLocal
   else
@@ -1033,7 +965,6 @@ _local_build() {
 
   _attention "Building local images"
 
-  _create_registry kind-registry 5000
   local BUILD_TARGETS=( assemble )
 
   cd "$ROOT/deltafi"
@@ -1045,7 +976,7 @@ _local_build() {
 
   if [[ -z "$NOCORE" ]]; then
     _attention "Building deltafi"
-    ./gradlew "${BUILD_TARGETS[@]}" -x test publishToMavenLocal docker dockerPushLocal || _exit_1 echo "Command 'gradlew \"${BUILD_TARGETS[@]}\" -x test publishToMavenLocal docker dockerPushLocal' failed"
+    ./gradlew "${BUILD_TARGETS[@]}" -x test publishToMavenLocal docker install || _exit_1 echo "Command 'gradlew \"${BUILD_TARGETS[@]}\" -x test publishToMavenLocal docker install' failed"
   fi
 
   export DELTAFI_PYTHON
@@ -1280,9 +1211,9 @@ _local_push() {
 _local_cluster() {
   local_build "$@"
   up
-  install -f deltafi/orchestration/charts/deltafi/values-kind.yaml -f deltafi/orchestration/charts/deltafi/values-local.yaml -f deltafi/orchestration/charts/deltafi/values-alerting-test.yaml
+  install -f deltafi/orchestration/charts/deltafi/values-kind.yaml -f deltafi/orchestration/charts/deltafi/values-alerting-test.yaml
   for plugin in "${PLUGINS[@]}"; do
-    run deltafi install-plugin "$plugin" -f "$plugin/charts/values-local.yaml"
+    run deltafi install-plugin "$plugin"
   done
 }
 
