Improved error outcomes with changelog script

diff --git a/utils/changelog b/utils/changelog
--- a/utils/changelog
+++ b/utils/changelog
@@ -64,6 +64,13 @@ _coalesce_markdown() {
   local path="$2"
   declare -A content=()
 
+  if ! compgen -G "${path}/*.md" > /dev/null; then
+    echo
+    echo "Error: There are no changelogs in ${path}"
+    echo
+    exit 1
+  fi
+
   for file in "${path}"/*.md; do
     local header=""
     while IFS= read -r line; do
@@ -151,7 +158,7 @@ else
       shift
       [[ -z "$1" ]] && _usage
       _revise_changelog "$@"
-      git rm "${UNRELEASED_DIR}/*.md"
+      rm -rf "${UNRELEASED_DIR}/*.md"
       ;;
     -d)
       _revise_changelog "dry-run" -d
